# Generated by Django 4.2.3 on 2023-07-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudProjet_api', '0002_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_name',
            field=models.CharField(default='', error_messages={'blank': "Le champ 'author_name' ne peut pas être vide."}, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='crudProjet_api.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='', error_messages={'blank': "Le champ 'title' ne peut pas être vide."}, max_length=100, unique=True),
        ),
    ]
