# Generated by Django 4.2.3 on 2023-07-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudProjet_api', '0007_alter_author_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(error_messages={'blank': "Le champ 'name' ne peut pas être vide."}, max_length=100, unique=True),
        ),
    ]
